export const SearchCriteriaTypes = [
  'YRKEN',
  'YRKESGRUPPER',
  'KOMPETENSER',
  'UTBILDNINGSNIVAER',
  'UTBILDNINGSINRIKTNINGAR',
  'KORKORT',
  'SPRAK',
  'KOMMUNER',
  'ANSTALLNINGSTYPER',
  'LAN',
  'LANDER',
  'YRKESERFARENHETER',
  'SPRAKNIVAER',
  'INGA_KVALIFIKATIONER'      
];